feature-138. Adding translation mock
systelab/systelab-translate pull request #139
Opened 2024-02-12 11:18 UTC by OscarDeDios

Added the possibility to use translation mock to avoid http access

2024-02-12 11:20 UTC, RubKrmon approved these changes
Thanks a lot

2024-02-12 11:22 UTC, Jbar91 approved these changes

2024-02-12 11:56 UTC, diegocj28 approved these changes
Thank you!

2024-02-13 07:01 UTC, fjaguado requested changes

2024-02-13 09:05 UTC, RubKrmon approved these changes

2024-02-13 10:17 UTC, OscarDeDios commented on projects/systelab-translate/package.json
> +  "version": "17.0.1",
Done

2024-02-13 11:24 UTC, fjaguado approved these changes

2024-02-13 11:25 UTC, merged