custom url added into lib.
systelab/systelab-translate pull request #48
Opened 2020-09-24 05:57 UTC by ricardmc

Small modifications have been applied but I have to say sorry. All linting and indentation changes have been declared as code changes.

So, if you need a short meeting/call to check the modifications, I'll be totally available for that.

2020-09-24 06:46 UTC, apenalver2 requested changes
Compilating using ng build --prod the process is crashing.

Please, can you fix it?

Thank you

2020-09-24 07:06 UTC, apenalver2 approved these changes

2020-09-28 12:42 UTC, alfonsserra requested changes

2020-09-28 12:42 UTC, alfonsserra commented on projects/systelab-translate/README.md
> +## Importing the library
This is part of How to use the library. It is a sub-case as it is not mandatory.

2020-09-28 12:42 UTC, alfonsserra commented on projects/systelab-translate/README.md
> +  let _translationFilesUrl = null
Do not use _ prefix. for variables. see Angular Code Conventions.
Assign to something.

2020-09-28 12:42 UTC, alfonsserra commented on projects/systelab-translate/README.md
> +###### restAPI usage:
It is not rest. It is direct http

2020-09-28 12:42 UTC, alfonsserra commented on projects/systelab-translate/README.md
> +  let _translationFilesUrl = './restAPI_URL_to_be_replaced';
Do not use _
Use const

2020-09-28 12:42 UTC, alfonsserra commented on projects/systelab-translate/src/lib/systelab-translate.module.ts
> +export interface ISystelabTranslateModule {
Do not use I prefix. We do not have that code convention.

Rename the interface to something like TranslationConfiguration

Make the customUrl optional.

2020-09-28 12:42 UTC, alfonsserra commented on projects/systelab-translate/src/lib/systelab-translate.module.ts
> +export const _translationFilesUrl = null;
Do not use _ prefix.

2021-04-20 15:40 UTC, olgapuig commented
@ricardmc Please, reject this pull-request in case it's no longer needed.

2021-07-13 05:58 UTC, closed without merging

2021-07-13 05:58 UTC, ricardmc commented
unnecessary change for the moment. I close it to allow angular 12 upgrade as Olga requested